/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ensinae.views;

import java.util.logging.Logger;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;



/**
 *
 * @author Victor
 */
public class TelaDisciplinas extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(TelaDisciplinas.class.getName());


    /**
     * Creates new form Vestibulares
     */
    public TelaDisciplinas() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icone.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnEntrarVest = new javax.swing.JButton();
        btnSobreVest = new javax.swing.JButton();
        btnInicioVest = new javax.swing.JButton();
        btnVestibularesDisc = new javax.swing.JButton();
        btnExtraDisc = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        portgues = new javax.swing.JPanel();
        btnAcessarPort = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Matematica = new javax.swing.JPanel();
        btnAcessarMatExtra1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fisica = new javax.swing.JPanel();
        btnAcessarfisic = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        biologia = new javax.swing.JPanel();
        btnAcessarBio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        btnEntrarVest.setBackground(new java.awt.Color(0, 51, 255));
        btnEntrarVest.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnEntrarVest.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarVest.setText("Sair");
        btnEntrarVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarVestActionPerformed(evt);
            }
        });

        btnSobreVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSobreVest.setText("Sobre Nós");
        btnSobreVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreVestActionPerformed(evt);
            }
        });

        btnInicioVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnInicioVest.setText("Início");
        btnInicioVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioVestActionPerformed(evt);
            }
        });

        btnVestibularesDisc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnVestibularesDisc.setText("Vestibulares");
        btnVestibularesDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVestibularesDiscActionPerformed(evt);
            }
        });

        btnExtraDisc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExtraDisc.setText("Extra");
        btnExtraDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraDiscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnInicioVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExtraDisc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVestibularesDisc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobreVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrarVest)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExtraDisc)
                    .addComponent(btnVestibularesDisc)
                    .addComponent(btnInicioVest)
                    .addComponent(btnSobreVest)
                    .addComponent(btnEntrarVest))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.setBackground(new java.awt.Color(250, 249, 246));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        portgues.setBackground(new java.awt.Color(0, 51, 255));
        portgues.setLayout(null);

        btnAcessarPort.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAcessarPort.setForeground(new java.awt.Color(0, 51, 255));
        btnAcessarPort.setText("Acesse as Aulas!");
        btnAcessarPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarPortActionPerformed(evt);
            }
        });
        portgues.add(btnAcessarPort);
        btnAcessarPort.setBounds(60, 190, 235, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/noslen.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        portgues.add(jLabel5);
        jLabel5.setBounds(-120, -70, 700, 410);

        jTabbedPane1.addTab("Português", portgues);

        Matematica.setBackground(new java.awt.Color(0, 51, 255));
        Matematica.setLayout(null);

        btnAcessarMatExtra1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAcessarMatExtra1.setForeground(new java.awt.Color(0, 51, 255));
        btnAcessarMatExtra1.setText("Acesse as Aulas!");
        btnAcessarMatExtra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarMatExtra1ActionPerformed(evt);
            }
        });
        Matematica.add(btnAcessarMatExtra1);
        btnAcessarMatExtra1.setBounds(60, 190, 235, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rafael.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Matematica.add(jLabel1);
        jLabel1.setBounds(-120, -70, 700, 410);

        jTabbedPane1.addTab("Matemática", Matematica);

        fisica.setBackground(new java.awt.Color(0, 51, 255));
        fisica.setLayout(null);

        btnAcessarfisic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAcessarfisic.setForeground(new java.awt.Color(0, 51, 255));
        btnAcessarfisic.setText("Acesse as Aulas!");
        btnAcessarfisic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarfisicActionPerformed(evt);
            }
        });
        fisica.add(btnAcessarfisic);
        btnAcessarfisic.setBounds(60, 190, 235, 32);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/coelho.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        fisica.add(jLabel3);
        jLabel3.setBounds(-120, -70, 700, 410);

        jTabbedPane1.addTab("Fisíca", fisica);

        biologia.setBackground(new java.awt.Color(0, 51, 255));
        biologia.setLayout(null);

        btnAcessarBio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAcessarBio.setForeground(new java.awt.Color(0, 51, 255));
        btnAcessarBio.setText("Acesse as Aulas!");
        btnAcessarBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarBioActionPerformed(evt);
            }
        });
        biologia.add(btnAcessarBio);
        btnAcessarBio.setBounds(60, 170, 235, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/landim.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        biologia.add(jLabel4);
        jLabel4.setBounds(-120, -70, 700, 410);

        jTabbedPane1.addTab("Biologia", biologia);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("UNESP");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarVestActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarVestActionPerformed

    private void btnSobreVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreVestActionPerformed
        // TODO add your handling code here:
        new TelaSobreNos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobreVestActionPerformed

    private void btnVestibularesDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVestibularesDiscActionPerformed
    new Vestibulares().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVestibularesDiscActionPerformed

    private void btnInicioVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioVestActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioVestActionPerformed

    private void btnExtraDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraDiscActionPerformed
        // TODO add your handling code here:
         new TelaMaterialExtra().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExtraDiscActionPerformed

    private void btnAcessarPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarPortActionPerformed
        // TODO add your handling code here:
        new TelaPortugues().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAcessarPortActionPerformed

    private void btnAcessarMatExtra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarMatExtra1ActionPerformed
        // TODO add your handling code here:
        new TelaMatematica().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAcessarMatExtra1ActionPerformed

    private void btnAcessarfisicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarfisicActionPerformed
        // TODO add your handling code here:
        new TelaFisica().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAcessarfisicActionPerformed

    private void btnAcessarBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarBioActionPerformed
        // TODO add your handling code here:
        new TelaBiologia().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAcessarBioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDisciplinas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Matematica;
    private javax.swing.JPanel biologia;
    private javax.swing.JButton btnAcessarBio;
    private javax.swing.JButton btnAcessarMatExtra1;
    private javax.swing.JButton btnAcessarPort;
    private javax.swing.JButton btnAcessarfisic;
    private javax.swing.JButton btnEntrarVest;
    private javax.swing.JButton btnExtraDisc;
    private javax.swing.JButton btnInicioVest;
    private javax.swing.JButton btnSobreVest;
    private javax.swing.JButton btnVestibularesDisc;
    private javax.swing.JPanel fisica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel portgues;
    // End of variables declaration//GEN-END:variables
}
