/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ensinae.views;

import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icone.png"));
        setIconImage(icon.getImage());

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrarPrincipal = new javax.swing.JButton();
        btnSobrePrincipal = new javax.swing.JButton();
        btnVestibularesPrincipal = new javax.swing.JButton();
        btnExtraPrincipal = new javax.swing.JButton();
        btnDisciplinasPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Venha conhecer nossos professores!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 230, 340, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/telaprincipal.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, -60, 730, 400);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        btnEntrarPrincipal.setBackground(new java.awt.Color(0, 51, 255));
        btnEntrarPrincipal.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnEntrarPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarPrincipal.setText("Sair");
        btnEntrarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarPrincipalActionPerformed(evt);
            }
        });

        btnSobrePrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSobrePrincipal.setText("Sobre Nós");
        btnSobrePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobrePrincipalActionPerformed(evt);
            }
        });

        btnVestibularesPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnVestibularesPrincipal.setText("Vestibulares");
        btnVestibularesPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVestibularesPrincipalActionPerformed(evt);
            }
        });

        btnExtraPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExtraPrincipal.setText("Extra");
        btnExtraPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraPrincipalActionPerformed(evt);
            }
        });

        btnDisciplinasPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDisciplinasPrincipal.setText("Disciplinas");
        btnDisciplinasPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinasPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnDisciplinasPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExtraPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVestibularesPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobrePrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrarPrincipal)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisciplinasPrincipal)
                    .addComponent(btnExtraPrincipal)
                    .addComponent(btnVestibularesPrincipal)
                    .addComponent(btnSobrePrincipal)
                    .addComponent(btnEntrarPrincipal))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSobrePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobrePrincipalActionPerformed
        // TODO add your handling code here:
        new TelaSobreNos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobrePrincipalActionPerformed

    private void btnExtraPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraPrincipalActionPerformed
        // TODO add your handling code here:
        new TelaMaterialExtra().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExtraPrincipalActionPerformed

    private void btnEntrarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarPrincipalActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarPrincipalActionPerformed

    private void btnVestibularesPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVestibularesPrincipalActionPerformed
        // TODO add your handling code here:
        new Vestibulares().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVestibularesPrincipalActionPerformed

    private void btnDisciplinasPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinasPrincipalActionPerformed
        // TODO add your handling code here:
        new TelaDisciplinas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDisciplinasPrincipalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new TelaDisciplinas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisciplinasPrincipal;
    private javax.swing.JButton btnEntrarPrincipal;
    private javax.swing.JButton btnExtraPrincipal;
    private javax.swing.JButton btnSobrePrincipal;
    private javax.swing.JButton btnVestibularesPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
