/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ensinae.views;

import java.util.logging.Logger;
import java.awt.Desktop;
import java.net.URI;



/**
 *
 * @author Victor
 */
public class TelaDisciplinas extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(TelaDisciplinas.class.getName());


    /**
     * Creates new form Vestibulares
     */
    public TelaDisciplinas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnEntrarVest = new javax.swing.JButton();
        btnSobreVest = new javax.swing.JButton();
        btnInicioVest = new javax.swing.JButton();
        btnVestibularesDisc = new javax.swing.JButton();
        btnExtraDisc = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Matematica1 = new javax.swing.JPanel();
        Matematica = new javax.swing.JPanel();
        fisica = new javax.swing.JPanel();
        biologia = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jLabel10.setText("jLabel10");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        btnEntrarVest.setBackground(new java.awt.Color(0, 51, 255));
        btnEntrarVest.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnEntrarVest.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarVest.setText("Sair");
        btnEntrarVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarVestActionPerformed(evt);
            }
        });

        btnSobreVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSobreVest.setText("Sobre Nós");
        btnSobreVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreVestActionPerformed(evt);
            }
        });

        btnInicioVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnInicioVest.setText("Início");
        btnInicioVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioVestActionPerformed(evt);
            }
        });

        btnVestibularesDisc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnVestibularesDisc.setText("Vestibulares");
        btnVestibularesDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVestibularesDiscActionPerformed(evt);
            }
        });

        btnExtraDisc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExtraDisc.setText("Extra");
        btnExtraDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraDiscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnInicioVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExtraDisc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVestibularesDisc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobreVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrarVest)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExtraDisc)
                    .addComponent(btnVestibularesDisc)
                    .addComponent(btnInicioVest)
                    .addComponent(btnSobreVest)
                    .addComponent(btnEntrarVest))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.setBackground(new java.awt.Color(250, 249, 246));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        Matematica1.setBackground(new java.awt.Color(0, 51, 255));
        Matematica1.setLayout(null);
        jTabbedPane1.addTab("Português", Matematica1);

        Matematica.setBackground(new java.awt.Color(0, 51, 255));
        Matematica.setLayout(null);
        jTabbedPane1.addTab("Matemática", Matematica);

        fisica.setBackground(new java.awt.Color(0, 51, 255));
        fisica.setLayout(null);
        jTabbedPane1.addTab("Fisíca", fisica);

        biologia.setBackground(new java.awt.Color(0, 51, 255));
        biologia.setLayout(null);
        jTabbedPane1.addTab("Biologia", biologia);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("UNESP");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarVestActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarVestActionPerformed

    private void btnSobreVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreVestActionPerformed
        // TODO add your handling code here:
        new TelaSobreNos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobreVestActionPerformed

    private void btnVestibularesDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVestibularesDiscActionPerformed
    new Vestibulares().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVestibularesDiscActionPerformed

    private void btnInicioVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioVestActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioVestActionPerformed

    private void btnExtraDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraDiscActionPerformed
        // TODO add your handling code here:
         new TelaMaterialExtra().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExtraDiscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDisciplinas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Matematica;
    private javax.swing.JPanel Matematica1;
    private javax.swing.JPanel biologia;
    private javax.swing.JButton btnEntrarVest;
    private javax.swing.JButton btnExtraDisc;
    private javax.swing.JButton btnInicioVest;
    private javax.swing.JButton btnSobreVest;
    private javax.swing.JButton btnVestibularesDisc;
    private javax.swing.JPanel fisica;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
