/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ensinae.views;

import java.util.logging.Logger;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;



/**
 *
 * @author Victor
 */
public class Vestibulares extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Vestibulares.class.getName());


    /**
     * Creates new form Vestibulares
     */
    public Vestibulares() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icone.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnEntrarVest = new javax.swing.JButton();
        btnSobreVest = new javax.swing.JButton();
        btnInicioVest = new javax.swing.JButton();
        btnExtraVest = new javax.swing.JButton();
        btnDisciplinasVest = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Enem = new javax.swing.JPanel();
        btnEnem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Fatec = new javax.swing.JPanel();
        btnFatec = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Unitau = new javax.swing.JPanel();
        btnUnitau = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Unisal = new javax.swing.JPanel();
        btnUnisal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        unesp = new javax.swing.JPanel();
        unesppp = new javax.swing.JPanel();
        btnUnesp = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        usp = new javax.swing.JPanel();
        btnUsp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Fuvest = new javax.swing.JPanel();
        btnFuvest = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        UFSC = new javax.swing.JPanel();
        btnUUFSC = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        UFJF = new javax.swing.JPanel();
        btnUFJF = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        UERJ = new javax.swing.JPanel();
        btnUERJ = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        btnEntrarVest.setBackground(new java.awt.Color(0, 51, 255));
        btnEntrarVest.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnEntrarVest.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarVest.setText("Sair");
        btnEntrarVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarVestActionPerformed(evt);
            }
        });

        btnSobreVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSobreVest.setText("Sobre Nós");
        btnSobreVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreVestActionPerformed(evt);
            }
        });

        btnInicioVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnInicioVest.setText("Início");
        btnInicioVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioVestActionPerformed(evt);
            }
        });

        btnExtraVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExtraVest.setText("Extra");
        btnExtraVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraVestActionPerformed(evt);
            }
        });

        btnDisciplinasVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDisciplinasVest.setText("Disciplinas");
        btnDisciplinasVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinasVestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisciplinasVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExtraVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobreVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrarVest)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisciplinasVest)
                    .addComponent(btnExtraVest)
                    .addComponent(btnInicioVest)
                    .addComponent(btnSobreVest)
                    .addComponent(btnEntrarVest))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.setBackground(new java.awt.Color(250, 249, 246));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        Enem.setBackground(new java.awt.Color(0, 51, 255));
        Enem.setLayout(null);

        btnEnem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnem.setForeground(new java.awt.Color(0, 51, 255));
        btnEnem.setText("ACESSAR O SITE");
        btnEnem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnemActionPerformed(evt);
            }
        });
        Enem.add(btnEnem);
        btnEnem.setBounds(280, 220, 360, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/enem.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        Enem.add(jLabel5);
        jLabel5.setBounds(0, -100, 700, 400);

        jTabbedPane1.addTab("Enem", Enem);

        Fatec.setBackground(new java.awt.Color(0, 51, 255));
        Fatec.setLayout(null);

        btnFatec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFatec.setForeground(new java.awt.Color(0, 51, 255));
        btnFatec.setText("ACESSAR O SITE");
        btnFatec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFatecActionPerformed(evt);
            }
        });
        Fatec.add(btnFatec);
        btnFatec.setBounds(280, 220, 360, 32);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fatec.png"))); // NOI18N
        jLabel7.setText("jLabel1");
        Fatec.add(jLabel7);
        jLabel7.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("Fatec", Fatec);

        Unitau.setBackground(new java.awt.Color(0, 51, 255));
        Unitau.setLayout(null);

        btnUnitau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUnitau.setForeground(new java.awt.Color(0, 51, 255));
        btnUnitau.setText("ACESSAR O SITE");
        btnUnitau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnitauActionPerformed(evt);
            }
        });
        Unitau.add(btnUnitau);
        btnUnitau.setBounds(280, 220, 360, 32);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/unitau.png"))); // NOI18N
        jLabel9.setText("jLabel1");
        Unitau.add(jLabel9);
        jLabel9.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("Unitau", Unitau);

        Unisal.setBackground(new java.awt.Color(0, 51, 255));
        Unisal.setLayout(null);

        btnUnisal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUnisal.setForeground(new java.awt.Color(0, 51, 255));
        btnUnisal.setText("ACESSAR O SITE");
        btnUnisal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnisalActionPerformed(evt);
            }
        });
        Unisal.add(btnUnisal);
        btnUnisal.setBounds(280, 220, 360, 32);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/unisal.png"))); // NOI18N
        jLabel11.setText("jLabel1");
        Unisal.add(jLabel11);
        jLabel11.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("Unisal", Unisal);

        unesppp.setBackground(new java.awt.Color(0, 51, 255));
        unesppp.setLayout(null);

        btnUnesp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUnesp.setForeground(new java.awt.Color(0, 51, 255));
        btnUnesp.setText("ACESSAR O SITE");
        btnUnesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnespActionPerformed(evt);
            }
        });
        unesppp.add(btnUnesp);
        btnUnesp.setBounds(280, 220, 360, 32);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/unesp.png"))); // NOI18N
        jLabel16.setText("jLabel1");
        unesppp.add(jLabel16);
        jLabel16.setBounds(0, -100, 730, 400);

        javax.swing.GroupLayout unespLayout = new javax.swing.GroupLayout(unesp);
        unesp.setLayout(unespLayout);
        unespLayout.setHorizontalGroup(
            unespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unesppp, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        unespLayout.setVerticalGroup(
            unespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unespLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(unesppp, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Unesp", unesp);

        usp.setBackground(new java.awt.Color(0, 51, 255));
        usp.setLayout(null);

        btnUsp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUsp.setForeground(new java.awt.Color(0, 51, 255));
        btnUsp.setText("ACESSAR O SITE");
        btnUsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUspActionPerformed(evt);
            }
        });
        usp.add(btnUsp);
        btnUsp.setBounds(280, 220, 360, 32);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usp.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        usp.add(jLabel6);
        jLabel6.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("USP", usp);

        Fuvest.setBackground(new java.awt.Color(0, 51, 255));
        Fuvest.setLayout(null);

        btnFuvest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFuvest.setForeground(new java.awt.Color(0, 51, 255));
        btnFuvest.setText("ACESSAR O SITE");
        btnFuvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuvestActionPerformed(evt);
            }
        });
        Fuvest.add(btnFuvest);
        btnFuvest.setBounds(280, 220, 360, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fuvest.png"))); // NOI18N
        jLabel8.setText("jLabel1");
        Fuvest.add(jLabel8);
        jLabel8.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("Fuvest", Fuvest);

        UFSC.setBackground(new java.awt.Color(0, 51, 255));
        UFSC.setLayout(null);

        btnUUFSC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUUFSC.setForeground(new java.awt.Color(0, 51, 255));
        btnUUFSC.setText("ACESSAR O SITE");
        btnUUFSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUUFSCActionPerformed(evt);
            }
        });
        UFSC.add(btnUUFSC);
        btnUUFSC.setBounds(280, 220, 360, 32);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usfc.png"))); // NOI18N
        jLabel13.setText("jLabel1");
        UFSC.add(jLabel13);
        jLabel13.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("UFSC", UFSC);

        UFJF.setBackground(new java.awt.Color(0, 51, 255));
        UFJF.setLayout(null);

        btnUFJF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUFJF.setForeground(new java.awt.Color(0, 51, 255));
        btnUFJF.setText("ACESSAR O SITE");
        btnUFJF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUFJFActionPerformed(evt);
            }
        });
        UFJF.add(btnUFJF);
        btnUFJF.setBounds(280, 220, 360, 32);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ufjf.png"))); // NOI18N
        jLabel14.setText("jLabel1");
        UFJF.add(jLabel14);
        jLabel14.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("UFJF", UFJF);

        UERJ.setBackground(new java.awt.Color(0, 51, 255));
        UERJ.setLayout(null);

        btnUERJ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUERJ.setForeground(new java.awt.Color(0, 51, 255));
        btnUERJ.setText("ACESSAR O SITE");
        btnUERJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUERJActionPerformed(evt);
            }
        });
        UERJ.add(btnUERJ);
        btnUERJ.setBounds(280, 220, 360, 32);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/uerj.png"))); // NOI18N
        jLabel15.setText("jLabel1");
        UERJ.add(jLabel15);
        jLabel15.setBounds(0, -100, 730, 400);

        jTabbedPane1.addTab("UERJ", UERJ);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("UNESP");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarVestActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarVestActionPerformed

    private void btnSobreVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreVestActionPerformed
        // TODO add your handling code here:
        new TelaSobreNos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobreVestActionPerformed

    private void btnExtraVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraVestActionPerformed
    new TelaMaterialExtra().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExtraVestActionPerformed

    private void btnEnemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnemActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://enem.inep.gov.br/participante/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEnemActionPerformed

    private void btnInicioVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioVestActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioVestActionPerformed

    private void btnDisciplinasVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinasVestActionPerformed
        // TODO add your handling code here:
        new TelaDisciplinas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDisciplinasVestActionPerformed

    private void btnFatecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFatecActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://vestibular.fatec.sp.gov.br/home/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFatecActionPerformed

    private void btnUnitauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnitauActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://unitau.br/vestibular/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUnitauActionPerformed

    private void btnUnisalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnisalActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://vestibular.unisal.br/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUnisalActionPerformed

    private void btnUnespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnespActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://vestibular.unesp.br/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUnespActionPerformed

    private void btnUspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUspActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://www.fuvest.br/enem-usp/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUspActionPerformed

    private void btnFuvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuvestActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://www.fuvest.br/vestibular-da-usp/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnFuvestActionPerformed

    private void btnUUFSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUUFSCActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://vestibularunificado2026.ufsc.br/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUUFSCActionPerformed

    private void btnUFJFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUFJFActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://www2.ufjf.br/copese/vestibular-pism-2/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUFJFActionPerformed

    private void btnUERJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUERJActionPerformed
        // TODO add your handling code here:
         try {
            Desktop.getDesktop().browse(new URI("https://www.vestibular.uerj.br/"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUERJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vestibulares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Enem;
    private javax.swing.JPanel Fatec;
    private javax.swing.JPanel Fuvest;
    private javax.swing.JPanel UERJ;
    private javax.swing.JPanel UFJF;
    private javax.swing.JPanel UFSC;
    private javax.swing.JPanel Unisal;
    private javax.swing.JPanel Unitau;
    private javax.swing.JButton btnDisciplinasVest;
    private javax.swing.JButton btnEnem;
    private javax.swing.JButton btnEntrarVest;
    private javax.swing.JButton btnExtraVest;
    private javax.swing.JButton btnFatec;
    private javax.swing.JButton btnFuvest;
    private javax.swing.JButton btnInicioVest;
    private javax.swing.JButton btnSobreVest;
    private javax.swing.JButton btnUERJ;
    private javax.swing.JButton btnUFJF;
    private javax.swing.JButton btnUUFSC;
    private javax.swing.JButton btnUnesp;
    private javax.swing.JButton btnUnisal;
    private javax.swing.JButton btnUnitau;
    private javax.swing.JButton btnUsp;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel unesp;
    private javax.swing.JPanel unesppp;
    private javax.swing.JPanel usp;
    // End of variables declaration//GEN-END:variables
}
