/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ensinae.views;

import java.util.logging.Logger;
import java.awt.Desktop;
import java.net.URI;



/**
 *
 * @author Victor
 */
public class Vestibulares extends javax.swing.JFrame {
    
    private static final Logger logger = Logger.getLogger(Vestibulares.class.getName());


    /**
     * Creates new form Vestibulares
     */
    public Vestibulares() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnEntrarVest = new javax.swing.JButton();
        btnSobreVest = new javax.swing.JButton();
        btnInicioVest = new javax.swing.JButton();
        btnExtraVest = new javax.swing.JButton();
        btnDisciplinasVest = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Fatec = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        unesp = new javax.swing.JPanel();
        unesppp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Enem = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Fuvest = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        UFSC = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        UERJ = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jLabel10.setText("jLabel10");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        btnEntrarVest.setBackground(new java.awt.Color(0, 51, 255));
        btnEntrarVest.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnEntrarVest.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrarVest.setText("Sair");
        btnEntrarVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarVestActionPerformed(evt);
            }
        });

        btnSobreVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSobreVest.setText("Sobre Nós");
        btnSobreVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreVestActionPerformed(evt);
            }
        });

        btnInicioVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnInicioVest.setText("Início");
        btnInicioVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioVestActionPerformed(evt);
            }
        });

        btnExtraVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExtraVest.setText("Extra");
        btnExtraVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraVestActionPerformed(evt);
            }
        });

        btnDisciplinasVest.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDisciplinasVest.setText("Disciplinas");
        btnDisciplinasVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinasVestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicioVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisciplinasVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExtraVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSobreVest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrarVest)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisciplinasVest)
                    .addComponent(btnExtraVest)
                    .addComponent(btnInicioVest)
                    .addComponent(btnSobreVest)
                    .addComponent(btnEntrarVest))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.setBackground(new java.awt.Color(250, 249, 246));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        Fatec.setBackground(new java.awt.Color(0, 51, 255));
        Fatec.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATAS IMPORTANTES");
        Fatec.add(jLabel3);
        jLabel3.setBounds(180, 10, 200, 30);

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INSCRIÇÕES:");
        Fatec.add(jLabel5);
        jLabel5.setBounds(170, 130, 130, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PROVA:");
        Fatec.add(jLabel7);
        jLabel7.setBounds(170, 160, 198, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RESULTADOS:");
        Fatec.add(jLabel9);
        jLabel9.setBounds(170, 190, 130, 20);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("ACESSAR O SITE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Fatec.add(jButton2);
        jButton2.setBounds(140, 240, 293, 32);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Fatec.add(jLabel19);
        jLabel19.setBounds(480, 240, 340, 210);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Fatec.add(jLabel20);
        jLabel20.setBounds(540, 190, 120, 170);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Fatec.add(jLabel21);
        jLabel21.setBounds(-50, 230, 340, 210);

        jTabbedPane1.addTab("Fatec", Fatec);

        unesppp.setBackground(new java.awt.Color(0, 51, 255));
        unesppp.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATAS IMPORTANTES");
        unesppp.add(jLabel1);
        jLabel1.setBounds(180, 10, 200, 30);

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INSCRIÇÕES:");
        unesppp.add(jLabel2);
        jLabel2.setBounds(170, 130, 130, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRIMEIRA FASE:");
        unesppp.add(jLabel4);
        jLabel4.setBounds(170, 160, 198, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SEGUNDA FASE:");
        unesppp.add(jLabel6);
        jLabel6.setBounds(170, 190, 130, 20);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("ACESSAR O SITE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        unesppp.add(jButton1);
        jButton1.setBounds(140, 240, 293, 32);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/6cad392f-727a-4be7-a414-c635fe6e75aa.png"))); // NOI18N
        unesppp.add(jLabel8);
        jLabel8.setBounds(150, 20, 320, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        unesppp.add(jLabel13);
        jLabel13.setBounds(480, 240, 340, 210);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        unesppp.add(jLabel14);
        jLabel14.setBounds(540, 190, 120, 170);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        unesppp.add(jLabel15);
        jLabel15.setBounds(-50, 230, 340, 210);

        javax.swing.GroupLayout unespLayout = new javax.swing.GroupLayout(unesp);
        unesp.setLayout(unespLayout);
        unespLayout.setHorizontalGroup(
            unespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(unesppp, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        unespLayout.setVerticalGroup(
            unespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unespLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(unesppp, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Unesp", unesp);

        Enem.setBackground(new java.awt.Color(0, 51, 255));
        Enem.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DATAS IMPORTANTES");
        Enem.add(jLabel17);
        jLabel17.setBounds(180, 10, 200, 30);

        jLabel22.setBackground(new java.awt.Color(0, 102, 153));
        jLabel22.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("INSCRIÇÕES:");
        Enem.add(jLabel22);
        jLabel22.setBounds(170, 130, 130, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PRIMEIRO DIA:");
        Enem.add(jLabel23);
        jLabel23.setBounds(170, 160, 198, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("SEGUNDO DIA:");
        Enem.add(jLabel24);
        jLabel24.setBounds(170, 190, 130, 20);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("ACESSAR O SITE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Enem.add(jButton3);
        jButton3.setBounds(140, 240, 293, 32);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Enem.add(jLabel28);
        jLabel28.setBounds(480, 240, 340, 210);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Enem.add(jLabel29);
        jLabel29.setBounds(540, 190, 120, 170);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Enem.add(jLabel30);
        jLabel30.setBounds(-50, 230, 340, 210);

        jTabbedPane1.addTab("Enem", Enem);

        Fuvest.setBackground(new java.awt.Color(0, 51, 255));
        Fuvest.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("DATAS IMPORTANTES");
        Fuvest.add(jLabel26);
        jLabel26.setBounds(180, 10, 200, 30);

        jLabel31.setBackground(new java.awt.Color(0, 102, 153));
        jLabel31.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("INSCRIÇÕES:");
        Fuvest.add(jLabel31);
        jLabel31.setBounds(170, 130, 130, 20);

        jLabel32.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("PRIMEIRA FASE:");
        Fuvest.add(jLabel32);
        jLabel32.setBounds(170, 160, 198, 20);

        jLabel33.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("SEGUNDA FASE:");
        Fuvest.add(jLabel33);
        jLabel33.setBounds(170, 190, 130, 20);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("ACESSAR O SITE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Fuvest.add(jButton4);
        jButton4.setBounds(140, 240, 293, 32);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Fuvest.add(jLabel37);
        jLabel37.setBounds(480, 240, 340, 210);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Fuvest.add(jLabel38);
        jLabel38.setBounds(540, 190, 120, 170);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        Fuvest.add(jLabel39);
        jLabel39.setBounds(-50, 230, 340, 210);

        jTabbedPane1.addTab("Fuvest", Fuvest);

        UFSC.setBackground(new java.awt.Color(0, 51, 255));
        UFSC.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("DATAS IMPORTANTES");
        UFSC.add(jLabel35);
        jLabel35.setBounds(180, 10, 200, 30);

        jLabel40.setBackground(new java.awt.Color(0, 102, 153));
        jLabel40.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("INSCRIÇÕES:");
        UFSC.add(jLabel40);
        jLabel40.setBounds(170, 130, 130, 20);

        jLabel41.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("PRIMEIRA FASE:");
        UFSC.add(jLabel41);
        jLabel41.setBounds(170, 160, 198, 20);

        jLabel42.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("SEGUNDA FASE:");
        UFSC.add(jLabel42);
        jLabel42.setBounds(170, 190, 130, 20);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 255));
        jButton5.setText("ACESSAR O SITE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        UFSC.add(jButton5);
        jButton5.setBounds(140, 240, 293, 32);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        UFSC.add(jLabel46);
        jLabel46.setBounds(480, 240, 340, 210);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        UFSC.add(jLabel47);
        jLabel47.setBounds(540, 190, 120, 170);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        UFSC.add(jLabel48);
        jLabel48.setBounds(-50, 230, 340, 210);

        jTabbedPane1.addTab("UFSC", UFSC);

        UERJ.setBackground(new java.awt.Color(0, 51, 255));
        UERJ.setLayout(null);

        jLabel44.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("DATAS IMPORTANTES");
        UERJ.add(jLabel44);
        jLabel44.setBounds(180, 10, 200, 30);

        jLabel49.setBackground(new java.awt.Color(0, 102, 153));
        jLabel49.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("INSCRIÇÕES:");
        UERJ.add(jLabel49);
        jLabel49.setBounds(170, 130, 130, 20);

        jLabel50.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("PRIMEIRA FASE:");
        UERJ.add(jLabel50);
        jLabel50.setBounds(170, 160, 198, 20);

        jLabel51.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("SEGUNDA FASE:");
        UERJ.add(jLabel51);
        jLabel51.setBounds(170, 190, 130, 20);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 255));
        jButton6.setText("ACESSAR O SITE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        UERJ.add(jButton6);
        jButton6.setBounds(140, 240, 293, 32);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        UERJ.add(jLabel55);
        jLabel55.setBounds(480, 240, 340, 210);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        UERJ.add(jLabel56);
        jLabel56.setBounds(540, 190, 120, 170);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/circulo.png"))); // NOI18N
        UERJ.add(jLabel57);
        jLabel57.setBounds(-50, 230, 340, 210);

        jTabbedPane1.addTab("UERJ", UERJ);

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("UNESP");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarVestActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarVestActionPerformed

    private void btnSobreVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreVestActionPerformed
        // TODO add your handling code here:
        new TelaSobreNos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSobreVestActionPerformed

    private void btnExtraVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraVestActionPerformed
    new TelaMaterialExtra().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnExtraVestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnInicioVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioVestActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioVestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://vestibular.unesp.br/"));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDisciplinasVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinasVestActionPerformed
        // TODO add your handling code here:
        new TelaDisciplinas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDisciplinasVestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vestibulares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Enem;
    private javax.swing.JPanel Fatec;
    private javax.swing.JPanel Fuvest;
    private javax.swing.JPanel UERJ;
    private javax.swing.JPanel UFSC;
    private javax.swing.JButton btnDisciplinasVest;
    private javax.swing.JButton btnEntrarVest;
    private javax.swing.JButton btnExtraVest;
    private javax.swing.JButton btnInicioVest;
    private javax.swing.JButton btnSobreVest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel unesp;
    private javax.swing.JPanel unesppp;
    // End of variables declaration//GEN-END:variables
}
